#define STACKSIZE 65536
#define DATASIZE 65536
#include <stdlib.h>
#include <stdio.h>
#include <string.h>

/*
 *              ======== DISCLAIMER ========
 * This program was generated by a program.  Do not use it to
 * learn how to write code.  This is not a good example. This
 * program likely has excessive amounts of very bad code, so
 * we are relying on the compiler to optimize many things.
 * This file was translated from a language called brainfun,
 * which is a fork of the language known as brainfuck.  Read
 * up on this online on Wikipedia.
 * 
 * Good luck, Treyzania
 * 
 */

// Registers
unsigned char* a;
unsigned char* b;
unsigned char* c;
unsigned char* d;

unsigned char* stack;
unsigned char* data;
unsigned char* sp; // Stack pointer.
unsigned char* dp; // Data pointer.

void push_stack(unsigned char b) {
    
    *sp = b;
    sp++;
    
}

void drop_stack_top(void) {
	
	*sp = 0;
	sp--;
	
}

unsigned char pop_stack(void) {
	
	unsigned char b = *sp;
	drop_stack_top(); // When you pop, it drops.
	
	return b;
	
}

void pushregs(void) {
	
	push_stack(*a);
	push_stack(*b);
	push_stack(*c);
	push_stack(*d);
	
}

void popregs(void) {
	
	// Reverse order because stacks are LIFO.
	*d = pop_stack();
	*c = pop_stack();
	*b = pop_stack();
	*a = pop_stack();
	
}

int main(void) {
	
	// Do the init assignments.
	
	// Allocate registers.
	a = malloc(sizeof(unsigned char));
	b = malloc(sizeof(unsigned char));
	c = malloc(sizeof(unsigned char));
	d = malloc(sizeof(unsigned char));
	
	// Allocate the stack and data body.
	stack = malloc(sizeof(unsigned char) * STACKSIZE);
	data = malloc(sizeof(unsigned char) * DATASIZE);
	
	// Allocate and assign stack and data pointers.
	sp = malloc(sizeof(unsigned char*));
	sp = stack;
	dp = malloc(sizeof(unsigned char*));
	dp = data;
	
	// All done the inits.  Now we actually run the program...
	
	*dp = 0x10;
	*a = *dp;
	*dp = getchar();
	push_stack(*dp);
	dp++;
	*dp = *a;
	--*dp;
	*a = *dp;
	dp--;
	
	while (*dp) {
		*dp = getchar();
		push_stack(*dp);
		dp++;
		*dp = *a;
		--*dp;
		*a = *dp;
		dp--;
		*dp = *a;
	}
	
	while (*dp) {
		*dp = pop_stack();
		putchar(*dp);
	}
	
	*dp = 0x00;
	
	return *dp;
	
}
